/// Drift table definitions + database for the example app.
///
/// Note: schema is created at runtime by `Migrator` (see
/// `lib/migrations/`), NOT by Drift's built-in `MigrationStrategy`. The
/// strategy below is a no-op so the two systems don't fight each other.
///
/// Generated by Drift codegen — see `database.g.dart`.
library;

import 'package:drift/drift.dart';

part 'database.g.dart';

/// Users — primary subject of most queries.
@DataClassName('UserRow')
class Users extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get email => text().unique()();
  TextColumn get name => text()();
  TextColumn get phone => text().withDefault(const Constant(''))();
  TextColumn get meta => text().nullable()();
  BoolColumn get active => boolean().withDefault(const Constant(true))();
  DateTimeColumn get createdAt => dateTime().nullable()();
  DateTimeColumn get updatedAt => dateTime().nullable()();
  DateTimeColumn get deletedAt => dateTime().nullable()();
}

/// Posts — hasMany target on User, belongsTo back to User.
@DataClassName('PostRow')
class Posts extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get userId => integer()();
  TextColumn get title => text()();
  TextColumn get body => text().withDefault(const Constant(''))();
}

/// Profiles — hasOne target on User.
@DataClassName('ProfileRow')
class Profiles extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get userId => integer()();
  TextColumn get bio => text().withDefault(const Constant(''))();
}

/// Roles — belongsToMany target on User.
@DataClassName('RoleRow')
class Roles extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
}

/// Pivot: User <-> Role.
@DataClassName('RoleUserRow')
class RoleUsers extends Table {
  IntColumn get userId => integer()();
  IntColumn get roleId => integer()();

  @override
  Set<Column> get primaryKey => {userId, roleId};
}

/// Single Drift database exposing all five tables.
///
/// `schemaVersion` and `migration` are no-ops because eloquent_flutter's
/// `Migrator` owns the schema lifecycle. Drift still uses `schemaVersion`
/// for its internal stream-key bookkeeping, so we keep it at 1.
@DriftDatabase(tables: [Users, Posts, Profiles, Roles, RoleUsers])
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.e);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {},
        onUpgrade: (m, from, to) async {},
      );
}